/**
 * Simple synchronous plugin that adds a footer to markdown content
 * Used for testing basic plugin functionality
 */

export const name = 'simple-plugin';
export const version = '1.0.0';
export const description = 'Adds a simple footer to markdown content';

export const params = [
	{
		name: 'footer',
		type: 'string',
		required: false,
		default: 'Generated by kustomark',
		description: 'Footer text to append'
	}
];

/**
 * Apply function - adds a footer to the content
 */
export const apply = (content, params, context) => {
	const footer = params.footer || 'Generated by kustomark';
	return `${content}\n\n---\n\n${footer}`;
};
