/**
 * Tests for plugin executor
 *
 * Tests plugin execution, timeout enforcement, parameter validation, and error handling
 */

import { describe, expect, test } from 'bun:test';
import { join } from 'node:path';
import {
	createPluginContext,
	executePlugin,
} from '../../src/core/plugin-executor.js';
import { loadPlugin } from '../../src/core/plugin-loader.js';
import {
	PluginTimeoutError,
	PluginParamValidationError,
	PluginExecutionError,
} from '../../src/core/plugin-errors.js';
import type { PluginConfig, KustomarkConfig } from '../../src/core/types.js';

const FIXTURES_DIR = join(process.cwd(), 'tests/fixtures/plugins');

// Mock config for testing
const mockConfig: KustomarkConfig = {
	apiVersion: 'kustomark/v1',
	kind: 'Kustomization',
	resources: ['**/*.md'],
};

describe('Plugin Executor', () => {
	describe('createPluginContext', () => {
		test('creates context with file path', () => {
			const context = createPluginContext(
				'/project/docs/api.md',
				mockConfig,
				'api.md',
			);

			expect(context.file).toBe('/project/docs/api.md');
			expect(context.relativePath).toBe('api.md');
		});

		test('context is readonly at top level', () => {
			const context = createPluginContext(
				'/project/docs/api.md',
				mockConfig,
				'api.md',
			);

			expect(() => {
				// @ts-expect-error - Testing immutability
				context.file = '/different/path';
			}).toThrow();
		});

		test('filters sensitive environment variables', () => {
			const context = createPluginContext(
				'/project/docs/api.md',
				mockConfig,
				'api.md',
			);

			// Should not include sensitive variables
			expect(context.env).not.toHaveProperty('PASSWORD');
			expect(context.env).not.toHaveProperty('SECRET');
			expect(context.env).not.toHaveProperty('TOKEN');
			expect(context.env).not.toHaveProperty('API_KEY');
		});

		test('includes safe environment variables', () => {
			// Set a safe env var for testing
			process.env.TEST_SAFE_VAR = 'safe-value';

			const context = createPluginContext(
				'/project/docs/api.md',
				mockConfig,
				'api.md',
			);

			expect(context.env.TEST_SAFE_VAR).toBe('safe-value');

			// Cleanup
			delete process.env.TEST_SAFE_VAR;
		});

		test('freezes env object to prevent modification', () => {
			const context = createPluginContext(
				'/project/docs/api.md',
				mockConfig,
				'api.md',
			);

			expect(() => {
				// @ts-expect-error - Testing immutability
				context.env.NEW_VAR = 'test';
			}).toThrow();
		});
	});

	describe('executePlugin - synchronous plugins', () => {
		test('executes simple synchronous plugin', async () => {
			const config: PluginConfig = {
				name: 'simple-plugin',
				source: join(FIXTURES_DIR, 'simple-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const result = await executePlugin(
				loaded,
				'# Hello\n\nContent here',
				{ footer: 'Custom footer' },
				context,
			);

			expect(result).toContain('# Hello');
			expect(result).toContain('Custom footer');
		});

		test('uses default parameters when not provided', async () => {
			const config: PluginConfig = {
				name: 'simple-plugin',
				source: join(FIXTURES_DIR, 'simple-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const result = await executePlugin(
				loaded,
				'# Hello',
				{}, // No params
				context,
			);

			expect(result).toContain('Generated by kustomark');
		});

		test('executes word counter plugin', async () => {
			const config: PluginConfig = {
				name: 'word-counter',
				source: join(FIXTURES_DIR, 'word-counter.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const result = await executePlugin(
				loaded,
				'Hello world this is a test',
				{},
				context,
			);

			expect(result).toContain('Words: 6');
			expect(result).toContain('Characters:');
		});

		test('respects plugin parameter options', async () => {
			const config: PluginConfig = {
				name: 'word-counter',
				source: join(FIXTURES_DIR, 'word-counter.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const result = await executePlugin(
				loaded,
				'Hello world',
				{ showChars: false },
				context,
			);

			expect(result).toContain('Words: 2');
			expect(result).not.toContain('Characters:');
		});
	});

	describe('executePlugin - asynchronous plugins', () => {
		test('executes async plugin', async () => {
			const config: PluginConfig = {
				name: 'async-plugin',
				source: join(FIXTURES_DIR, 'async-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const result = await executePlugin(
				loaded,
				'Content',
				{ delay: 10, prefix: '[TEST]' },
				context,
			);

			expect(result).toBe('[TEST] Content');
		});

		test('waits for async operations to complete', async () => {
			const config: PluginConfig = {
				name: 'async-plugin',
				source: join(FIXTURES_DIR, 'async-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const startTime = Date.now();
			await executePlugin(
				loaded,
				'Content',
				{ delay: 100 },
				context,
			);
			const elapsed = Date.now() - startTime;

			expect(elapsed).toBeGreaterThanOrEqual(100);
		});
	});

	describe('executePlugin - parameter validation', () => {
		test('runs validation before execution', async () => {
			const config: PluginConfig = {
				name: 'validator-plugin',
				source: join(FIXTURES_DIR, 'validator-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			await expect(
				executePlugin(
					loaded,
					'Content',
					{}, // Missing required param
					context,
				),
			).rejects.toThrow(PluginParamValidationError);
		});

		test('executes when validation passes', async () => {
			const config: PluginConfig = {
				name: 'validator-plugin',
				source: join(FIXTURES_DIR, 'validator-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const result = await executePlugin(
				loaded,
				'Content',
				{ required: 'value' },
				context,
			);

			expect(result).toBe('[VALIDATED] Content');
		});

		test('validates number constraints', async () => {
			const config: PluginConfig = {
				name: 'validator-plugin',
				source: join(FIXTURES_DIR, 'validator-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			await expect(
				executePlugin(
					loaded,
					'Content',
					{ required: 'value', minValue: -5 },
					context,
				),
			).rejects.toThrow(PluginParamValidationError);
		});

		test('validates enum constraints', async () => {
			const config: PluginConfig = {
				name: 'validator-plugin',
				source: join(FIXTURES_DIR, 'validator-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			await expect(
				executePlugin(
					loaded,
					'Content',
					{ required: 'value', choices: 'invalid' },
					context,
				),
			).rejects.toThrow(PluginParamValidationError);
		});

		test('provides detailed validation error messages', async () => {
			const config: PluginConfig = {
				name: 'toc-generator',
				source: join(FIXTURES_DIR, 'toc-generator.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			try {
				await executePlugin(
					loaded,
					'Content',
					{ maxDepth: 10 }, // Invalid - must be 1-6
					context,
				);
				expect.unreachable('Should have thrown');
			} catch (error) {
				expect(error).toBeInstanceOf(PluginParamValidationError);
				if (error instanceof PluginParamValidationError) {
					expect(error.errors[0].param).toBe('maxDepth');
					expect(error.errors[0].expected).toBe('1-6');
				}
			}
		});
	});

	describe('executePlugin - timeout enforcement', () => {
		test('enforces timeout for slow plugins', async () => {
			const config: PluginConfig = {
				name: 'timeout-plugin',
				source: join(FIXTURES_DIR, 'timeout-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			await expect(
				executePlugin(
					loaded,
					'Content',
					{ delay: 60000 }, // 60 seconds
					context,
					{ timeout: 100 }, // 100ms timeout
				),
			).rejects.toThrow(PluginTimeoutError);
		}, 1000); // Test timeout

		test('uses plugin-specific timeout from config', async () => {
			const config: PluginConfig = {
				name: 'timeout-plugin',
				source: join(FIXTURES_DIR, 'timeout-plugin.js'),
				timeout: 50, // Very short timeout
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			await expect(
				executePlugin(
					loaded,
					'Content',
					{ delay: 1000 },
					context,
				),
			).rejects.toThrow(PluginTimeoutError);
		}, 1000);

		test('does not timeout for fast plugins', async () => {
			const config: PluginConfig = {
				name: 'async-plugin',
				source: join(FIXTURES_DIR, 'async-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const result = await executePlugin(
				loaded,
				'Content',
				{ delay: 10 },
				context,
				{ timeout: 1000 },
			);

			expect(result).toContain('Content');
		});

		test('timeout error includes plugin name and file', async () => {
			const config: PluginConfig = {
				name: 'timeout-plugin',
				source: join(FIXTURES_DIR, 'timeout-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			try {
				await executePlugin(
					loaded,
					'Content',
					{ delay: 5000 },
					context,
					{ timeout: 50 },
				);
				expect.unreachable('Should have thrown');
			} catch (error) {
				expect(error).toBeInstanceOf(PluginTimeoutError);
				if (error instanceof PluginTimeoutError) {
					expect(error.pluginName).toBe('timeout-plugin');
					expect(error.file).toBe('/project/test.md');
					expect(error.timeoutMs).toBe(50);
				}
			}
		}, 1000);
	});

	describe('executePlugin - error handling', () => {
		test('throws PluginExecutionError for runtime errors', async () => {
			const config: PluginConfig = {
				name: 'error-plugin',
				source: join(FIXTURES_DIR, 'error-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			await expect(
				executePlugin(
					loaded,
					'Content',
					{ errorType: 'runtime' },
					context,
				),
			).rejects.toThrow(PluginExecutionError);
		});

		test('validates return type is string', async () => {
			const config: PluginConfig = {
				name: 'error-plugin',
				source: join(FIXTURES_DIR, 'error-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			await expect(
				executePlugin(
					loaded,
					'Content',
					{ errorType: 'type' },
					context,
				),
			).rejects.toThrow(PluginExecutionError);
		});

		test('error includes plugin name and file context', async () => {
			const config: PluginConfig = {
				name: 'error-plugin',
				source: join(FIXTURES_DIR, 'error-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			try {
				await executePlugin(
					loaded,
					'Content',
					{ errorType: 'runtime' },
					context,
				);
				expect.unreachable('Should have thrown');
			} catch (error) {
				expect(error).toBeInstanceOf(PluginExecutionError);
				if (error instanceof PluginExecutionError) {
					expect(error.pluginName).toBe('error-plugin');
					expect(error.file).toBe('/project/test.md');
					expect(error.message).toContain('Runtime error');
				}
			}
		});

		test('preserves original error as cause', async () => {
			const config: PluginConfig = {
				name: 'error-plugin',
				source: join(FIXTURES_DIR, 'error-plugin.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			try {
				await executePlugin(
					loaded,
					'Content',
					{ errorType: 'runtime' },
					context,
				);
				expect.unreachable('Should have thrown');
			} catch (error) {
				expect(error).toBeInstanceOf(PluginExecutionError);
				if (error instanceof PluginExecutionError) {
					expect(error.cause).toBeTruthy();
					expect(error.cause?.message).toContain('Runtime error');
				}
			}
		});
	});

	describe('executePlugin - TOC generator integration', () => {
		test('generates table of contents from headers', async () => {
			const config: PluginConfig = {
				name: 'toc-generator',
				source: join(FIXTURES_DIR, 'toc-generator.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const content = `
# Main Title

## Section 1

### Subsection 1.1

## Section 2
`;

			const result = await executePlugin(
				loaded,
				content,
				{},
				context,
			);

			expect(result).toContain('Table of Contents');
			expect(result).toContain('[Main Title]');
			expect(result).toContain('[Section 1]');
			expect(result).toContain('[Subsection 1.1]');
		});

		test('respects maxDepth parameter', async () => {
			const config: PluginConfig = {
				name: 'toc-generator',
				source: join(FIXTURES_DIR, 'toc-generator.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const content = `
# Main Title

## Section 1

### Subsection 1.1

#### Deep Section
`;

			const result = await executePlugin(
				loaded,
				content,
				{ maxDepth: 2 },
				context,
			);

			expect(result).toContain('[Main Title]');
			expect(result).toContain('[Section 1]');
			expect(result).not.toContain('[Subsection 1.1]');
			expect(result).not.toContain('[Deep Section]');
		});

		test('uses custom title when provided', async () => {
			const config: PluginConfig = {
				name: 'toc-generator',
				source: join(FIXTURES_DIR, 'toc-generator.js'),
			};

			const loaded = await loadPlugin(config, config.source);
			const context = createPluginContext('/project/test.md', mockConfig, 'test.md');

			const content = '# Main Title\n\n## Section 1';

			const result = await executePlugin(
				loaded,
				content,
				{ title: 'Contents' },
				context,
			);

			expect(result).toContain('## Contents');
			expect(result).not.toContain('Table of Contents');
		});
	});
});
