import { describe, expect, test } from "bun:test";
import { validateConfig } from "../../src/core/config-parser.js";
import { applyAppendToFile, applyPatches, applyPrependToFile } from "../../src/core/patch-engine.js";

// ──────────────────────────────────────────────────────────────────
// applyPrependToFile
// ──────────────────────────────────────────────────────────────────

const DOC = "# My Document\n\nSome content here.\n\n## Section\n\nMore content.";

describe("applyPrependToFile", () => {
  test("prepends content to beginning of file", () => {
    const result = applyPrependToFile(DOC, "<!-- AUTO-GENERATED -->\n\n");
    expect(result.count).toBe(1);
    expect(result.content).toBe("<!-- AUTO-GENERATED -->\n\n" + DOC);
  });

  test("always returns count=1", () => {
    const result = applyPrependToFile(DOC, "prefix");
    expect(result.count).toBe(1);
  });

  test("prepends to empty file", () => {
    const result = applyPrependToFile("", "# New Header\n");
    expect(result.count).toBe(1);
    expect(result.content).toBe("# New Header\n");
  });

  test("prepends empty string (no-op content)", () => {
    const result = applyPrependToFile(DOC, "");
    expect(result.count).toBe(1);
    expect(result.content).toBe(DOC);
  });

  test("prepends multiline content", () => {
    const prefix = "---\nautogenerated: true\n---\n\n";
    const result = applyPrependToFile(DOC, prefix);
    expect(result.content).toStartWith("---\nautogenerated: true\n---\n\n");
    expect(result.content).toContain("# My Document");
  });

  test("original content is preserved intact after prepend", () => {
    const result = applyPrependToFile(DOC, "HEADER\n\n");
    expect(result.content).toContain(DOC);
    expect(result.content.indexOf(DOC)).toBe("HEADER\n\n".length);
  });

  test("prepends before frontmatter if file starts with frontmatter", () => {
    const docWithFrontmatter = "---\ntitle: Test\n---\n\n# Content";
    const result = applyPrependToFile(docWithFrontmatter, "<!-- gen -->\n");
    expect(result.content).toStartWith("<!-- gen -->\n---\ntitle: Test\n---");
  });
});

// ──────────────────────────────────────────────────────────────────
// applyAppendToFile
// ──────────────────────────────────────────────────────────────────

describe("applyAppendToFile", () => {
  test("appends content to end of file", () => {
    const result = applyAppendToFile(DOC, "\n\n---\n*Generated by kustomark*\n");
    expect(result.count).toBe(1);
    expect(result.content).toBe(DOC + "\n\n---\n*Generated by kustomark*\n");
  });

  test("always returns count=1", () => {
    const result = applyAppendToFile(DOC, "suffix");
    expect(result.count).toBe(1);
  });

  test("appends to empty file", () => {
    const result = applyAppendToFile("", "# Footer\n");
    expect(result.count).toBe(1);
    expect(result.content).toBe("# Footer\n");
  });

  test("appends empty string (no-op content)", () => {
    const result = applyAppendToFile(DOC, "");
    expect(result.count).toBe(1);
    expect(result.content).toBe(DOC);
  });

  test("appends multiline footer", () => {
    const footer = "\n\n---\n\n*Last updated: 2026*\n*Auto-generated*\n";
    const result = applyAppendToFile(DOC, footer);
    expect(result.content).toEndWith(footer);
    expect(result.content).toContain(DOC);
  });

  test("original content is preserved intact before append", () => {
    const suffix = "\nFOOTER";
    const result = applyAppendToFile(DOC, suffix);
    expect(result.content).toStartWith(DOC);
  });
});

// ──────────────────────────────────────────────────────────────────
// Integration via applyPatches
// ──────────────────────────────────────────────────────────────────

describe("prepend-to-file / append-to-file via applyPatches", () => {
  test("prepend-to-file patch applies correctly", async () => {
    const result = await applyPatches(DOC, [
      { op: "prepend-to-file", content: "<!-- header -->\n\n" },
    ]);
    expect(result.content).toStartWith("<!-- header -->\n\n");
    expect(result.content).toContain("# My Document");
    expect(result.applied).toBe(1);
  });

  test("append-to-file patch applies correctly", async () => {
    const result = await applyPatches(DOC, [
      { op: "append-to-file", content: "\n\n<!-- footer -->" },
    ]);
    expect(result.content).toEndWith("\n\n<!-- footer -->");
    expect(result.content).toContain("# My Document");
    expect(result.applied).toBe(1);
  });

  test("prepend and append can be chained", async () => {
    const result = await applyPatches(DOC, [
      { op: "prepend-to-file", content: "HEADER\n\n" },
      { op: "append-to-file", content: "\n\nFOOTER" },
    ]);
    expect(result.content).toStartWith("HEADER\n\n");
    expect(result.content).toEndWith("\n\nFOOTER");
    expect(result.content).toContain(DOC);
  });

  test("prepend-to-file with onNoMatch=skip still applies (always matches)", async () => {
    const result = await applyPatches(
      DOC,
      [{ op: "prepend-to-file", content: "HEADER\n\n", onNoMatch: "skip" }],
    );
    // prepend-to-file always succeeds (count=1), onNoMatch is irrelevant
    expect(result.content).toStartWith("HEADER\n\n");
  });

  test("append-to-file with onNoMatch=skip still applies (always matches)", async () => {
    const result = await applyPatches(
      DOC,
      [{ op: "append-to-file", content: "\n\nFOOTER", onNoMatch: "skip" }],
    );
    expect(result.content).toEndWith("\n\nFOOTER");
  });
});

// ──────────────────────────────────────────────────────────────────
// Config validation
// ──────────────────────────────────────────────────────────────────

describe("prepend-to-file / append-to-file config validation", () => {
  const baseConfig = {
    apiVersion: "kustomark/v1",
    kind: "Kustomization",
    resources: ["*.md"],
    output: "out/",
  };

  test("valid prepend-to-file config passes", () => {
    const result = validateConfig({
      ...baseConfig,
      patches: [{ op: "prepend-to-file", content: "<!-- gen -->\n" }],
    });
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  test("valid append-to-file config passes", () => {
    const result = validateConfig({
      ...baseConfig,
      patches: [{ op: "append-to-file", content: "\n---\nfooter\n" }],
    });
    expect(result.valid).toBe(true);
    expect(result.errors).toHaveLength(0);
  });

  test("prepend-to-file without content fails validation", () => {
    const result = validateConfig({
      ...baseConfig,
      patches: [{ op: "prepend-to-file" }],
    });
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.field.includes("content"))).toBe(true);
  });

  test("append-to-file without content fails validation", () => {
    const result = validateConfig({
      ...baseConfig,
      patches: [{ op: "append-to-file" }],
    });
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.field.includes("content"))).toBe(true);
  });

  test("prepend-to-file with non-string content fails validation", () => {
    const result = validateConfig({
      ...baseConfig,
      patches: [{ op: "prepend-to-file", content: 42 }],
    });
    expect(result.valid).toBe(false);
    expect(result.errors.some((e) => e.field.includes("content"))).toBe(true);
  });
});
